apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sheren04-dev
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsNonRoot: true      # ← OpenShift requirement
      containers:
      - name: backend
        image: sheren04/bbmsup-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: bloodbank-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: bloodbank-config
              key: NODE_ENV
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: bloodbank-config
              key: FRONTEND_URL
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: bloodbank-secret
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: bloodbank-secret
              key: JWT_SECRET
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
